import './globals.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Header from './components/header';
import Footer from './components/footer';
import BackgroundShapes from './components/background-shapes';

const Fira_Code = localFont({ src: '../public/fonts/Fira_Code/FiraCode-VariableFont_wght.ttf' });
const DM_Sans = localFont({ src: '../public/fonts/DM_Sans/DMSans-VariableFont_opsz_wght.ttf' });

export const metadata: Metadata = {
  title: 'Frontend Mentor | Personal Blog',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${Fira_Code.className} ${DM_Sans.className}`}>
        <BackgroundShapes />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
