// Next
import type {Metadata} from "next";
import localFont from "next/font/local";
// Styles
import "./globals.css";
// Components
import Header from "@/components/header";

const myFont = localFont({src: "../public/fonts/PublicSans-VariableFont_wght.ttf"});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
