// Fonts
import {Outfit} from "next/font/google";
// Styles
import "./globals.css";
// Components
import Header from "@/components/header";
import Search from "@/components/search";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["300", "500"],
  display: "swap",
});

export const metadata = {
  title: "Frontend Mentor | Entertainment Web App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Header />
        <main>
          <Search />
          {children}
        </main>
      </body>
    </html>
  );
}
